apiVersion: v1
kind: ConfigMap
metadata:
  name: i-can-do-it-config
  namespace: icdi
data:
  NEXT_PUBLIC_FIREBASE_CLIENT_APPID: "1:596514055680:web:5e9c9b6ef19ed0e4a75ae5"
  NEXT_PUBLIC_FIREBASE_CLIENT_MESSAGINGSENDERID: "596514055680"
  NEXT_PUBLIC_FIREBASE_CLIENT_STORAGEBUCKET: "i-can-do-it-45786.appspot.com"
  NEXT_PUBLIC_FIREBASE_CLIENT_PROJECTID: "i-can-do-it-45786"
  NEXT_PUBLIC_FIREBASE_CLIENT_AUTHDOMAIN: "i-can-do-it-45786.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_CLIENT_APIKEY: "AIzaSyDH-DGU-LZTDIjnHuP9r_ztgUFG33P031g"
  NEXT_PUBLIC_EMULATOR_FIRESTORE_PORT: "8080"
  NEXT_PUBLIC_EMULATOR_AUTH_PORT: "9099"
  NEXT_PUBLIC_EMULATOR_STORAGE_PORT: "9199"
---
apiVersion: v1
kind: Secret
metadata:
  name: i-can-do-it-secret
  namespace: icdi
type: Opaque
data:
  FIREBASE_SERVICE_ACCOUNT_KEY: eyJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsICJwcm9qZWN0X2lkIjogImktY2FuLWRvLWl0LTQ1Nzg2IiwgInByaXZhdGVfa2V5X2lkIjogIjc0MGFmMjYwYTZkNDIyYWJhOWQzNDNmZDI3ZTE1MDliMDM1NTEzZGMiLCAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUURQa0s0bmFMTzhPS1F2XG45bkovZGt0VDZocUpyamNWc1BUNnlvbmcrVG9Yc05mRVU3QUxvQXRnM1Jram1xNWtXNUVDRXUvbXBkTFdGMk5YXG5MY3RweVhJZ25mK0JMZGFyWENLellkUkVpYUU2aXlIN2xVZDlPdjV3Y2Nmd0hBVmxxczg5LzF0UXZuaW42bW00XG5lbWQwcy9DUWFHNlA5dWN4Z09mQ1doMXQ2eFNCOFFzcldVSFU1eUJjZUx0NXZYUE5LUDlHaVhHNmY2MjIvRklPXG5hNVJSbDA2WTRyS3R4QzdyNmk2TUt2cHQ4djBHM0NvY1RWbzErQ21XU1FIS3lwcU0wOStyak5sQU1URk5rYVZiXG5xQk5uaHE2azJST2VVNkpDOU0zQTlnQUo3TXhQU2FmRjJEeHlzMUNmK2pjejc5Ri94cU5LdjJDWGw3bUd2TWFMXG5LbkZGWFQvbkFnTUJBQUVDZ2dFQUp2SGVBMDN0WDFUL1ZYSjN0RHUxVVliY3VOV0R4MkdlN1lsZ0NtS295RFlwXG5uZEFYK1c1cmhCNm43MXEvK3R1Rlh5Ni9iWGJTa3RIcmxUbGw3N0RZNVk3UG1HVEo0UGdXR0xNejJUSTdtcGp0XG5aTjl5L09lN1Fzek9kMXBDbHZ0UURERmo2RWY4cW9EY21qejVPVmZqdkt5amhnYU5CV2hLMDlnRnFwQ1BsZnVXXG5FY0YvaW5hSHpyV2xobGlnUXVqbkwwVTBFMlVEOSsvMGNDcEFIbnU0TW10OFNNd05FQnFuT1YvMlJIOEhKbzVTXG56MThDSkMxbkpOdTJWYmhsaGNpcTZ1Z1NKcTNxQTF3eVJIQ2JTRlVOemRQbC93YVQzeDk0ZjRNMzBrZnpvcCtsXG5IaFpUODVrY3BKRG9JYWN3WXhEYXhLTUp2OU5jWlBjejRVN1V3Q0NINlFLQmdRRHQ1Zi9KSGxyR2xCOFNQVFBvXG4zQWdReFh4MmxrbVllTXJYRVFnZi8rYitMTFlYUFY0dHlJdEZldUpxdWpTSTJ2R1RzTS9QV091eStVZS9XelkvXG5sMnY5WXZaZ3FWVlFPWnpnWDNsOCtvWnJEVHdSN3Y3Z3FRSXFDb05pUWJuc282cjlYdCtxNyt2amRnWUo4ZUg0XG54R1grdHRlYmREblRxR21JOVowaE5jTVVtUUtCZ1FEZlc5SjNDYmZvb0hENU1SVnU3ZVgxeHRhTm1jRElGQndDXG5IM3hwRFJxblRBdjlkWWlqd0dueXNoaHN6TkJ3TkN2dU91Y2RiMitqVmx2ZXNab1lwWVVFRE9FYkVNQ2M0VHlpXG5QdkRGaFB6amRwbkYzUDd4V0d4cTFmRTRQNFJKc3h2WVNFWkxpanNhRDdpT3d5S2MxMHBwWm00d203cXBtZXdyXG5VMlU4TGdOSWZ3S0JnUURZZitucUkvL0VuR1F5ZXhSVXBIbUttYzhOTlBSQkdCeXc0TVVlS2dzVDRhak5PWUlOXG45R1lha3h5ZXVGcTYrVlhFYkxLU0pvQkozbWFYRlBFbnFpd1M2dzhCSk5tSkt3VkRoRi9SaDBUeEE1aFpVY0VPXG52NEJDdGxLZkJ1V25IOE9xMWI2RGw5aDZwcHdVVE5helNEanlOMys3NzJmNDRWazUxUnhzYnJyY2NRS0JnUUNSXG50aE5OT1BmVE9LZTZ5VHlVUzNxVHBnM2Qvb24zZkxidzQ1MkQ0dHFhZlUvdEg3bnVLZDUwUjU4TGkyb0hhT0duXG4zcUZiWUpGUjIwcS9zdGsyYnZTaHVjMDRuT3NxN1AxalV2QTd5eEEzUyszeFdNU3dxZURBcWFWZDdvSGNtbzMxXG53T0NxOHhpdlhjWW16RUpPVTF6bCtiNjAwME1vMVpOdWlFOG92VlBDL1FLQmdDUE0vbysrY2ZpeEZwY2d4bWxqXG5DOXppcDAxMXNSZWNVcC93czR2ZVNFK1dCREVBWWRiL1ZUVjFSZTJHTm02M0NxbzRJdVh6QnF6VmpTRkJlMnp2XG5Ydlo2T2tNR1RXbjZKTEZFOEhaY0xVbXVLMXFYQnBCN3ZnMDRObDlpeEVjTlVocXNJelpCY2tSTjFwSnB4NHhMXG5wUzJURDJKaXN5RFV2WG1WL2R3S2dRZHZcbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsICJjbGllbnRfZW1haWwiOiAiZmlyZWJhc2UtYWRtaW5zZGstcGtydjFAaS1jYW4tZG8taXQtNDU3ODYuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLCAiY2xpZW50X2lkIjogIjEwNzM1NTYyNjA0ODYwODUwODMzOSIsICJhdXRoX3VyaSI6ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4iLCAiYXV0aF9wcm92aWRlcl94NTA5X2NlcnRfdXJsIjogImh0dHBzOi8vd3d3Lmdvb2dsZWFwaXMuY29tL29hdXRoMi92MS9jZXJ0cyIsICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2ZpcmViYXNlLWFkbWluc2RrLXBrcnYxJTQwaS1jYW4tZG8taXQtNDU3ODYuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iIH0=
---
apiVersion: v1
kind: Service
metadata:
  name: i-can-do-it
  namespace: icdi
spec:
  selector:
    app: i-can-do-it
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: i-can-do-it
  namespace: icdi
spec:
  selector:
    matchLabels:
      app: i-can-do-it
  template:
    metadata:
      labels:
        app: i-can-do-it
    spec:
      containers:
        - name: i-can-do-it
          image: ghcr.io/reyhanardiya/reyhan-projects-k8s-icdi:main
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
          env:
            # - name: NODE_ENV
            #   value: staging
            - name: FIREBASE_SERVICE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: i-can-do-it-secret
                  key: FIREBASE_SERVICE_ACCOUNT_KEY
            - name: NEXT_PUBLIC_FIREBASE_CLIENT_APPID
              valueFrom:
                configMapKeyRef:
                  name: i-can-do-it-config
                  key: NEXT_PUBLIC_FIREBASE_CLIENT_APPID
            - name: NEXT_PUBLIC_FIREBASE_CLIENT_MESSAGINGSENDERID
              valueFrom:
                configMapKeyRef:
                  name: i-can-do-it-config
                  key: NEXT_PUBLIC_FIREBASE_CLIENT_MESSAGINGSENDERID
            - name: NEXT_PUBLIC_FIREBASE_CLIENT_STORAGEBUCKET
              valueFrom:
                configMapKeyRef:
                  name: i-can-do-it-config
                  key: NEXT_PUBLIC_FIREBASE_CLIENT_STORAGEBUCKET
            - name: NEXT_PUBLIC_FIREBASE_CLIENT_PROJECTID
              valueFrom:
                configMapKeyRef:
                  name: i-can-do-it-config
                  key: NEXT_PUBLIC_FIREBASE_CLIENT_PROJECTID
            - name: NEXT_PUBLIC_FIREBASE_CLIENT_AUTHDOMAIN
              valueFrom:
                configMapKeyRef:
                  name: i-can-do-it-config
                  key: NEXT_PUBLIC_FIREBASE_CLIENT_AUTHDOMAIN
            - name: NEXT_PUBLIC_FIREBASE_CLIENT_APIKEY
              valueFrom:
                configMapKeyRef:
                  name: i-can-do-it-config
                  key: NEXT_PUBLIC_FIREBASE_CLIENT_APIKEY
            - name: NEXT_PUBLIC_EMULATOR_FIRESTORE_PORT
              valueFrom:
                configMapKeyRef:
                  name: i-can-do-it-config
                  key: NEXT_PUBLIC_EMULATOR_FIRESTORE_PORT
            - name: NEXT_PUBLIC_EMULATOR_AUTH_PORT
              valueFrom:
                configMapKeyRef:
                  name: i-can-do-it-config
                  key: NEXT_PUBLIC_EMULATOR_AUTH_PORT
            - name: NEXT_PUBLIC_EMULATOR_STORAGE_PORT
              valueFrom:
                configMapKeyRef:
                  name: i-can-do-it-config
                  key: NEXT_PUBLIC_EMULATOR_STORAGE_PORT
        - name: firebase-emulator
          image: andreysenov/firebase-tools:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          securityContext:
            privileged: true
          ports:
            - containerPort: 4000
              name: ui
            - containerPort: 5000
              name: hosting
            - containerPort: 5001
              name: functions
            - containerPort: 8080
              name: firestore
            - containerPort: 8085
              name: pub-sub
            - containerPort: 9000
              name: realtime
            - containerPort: 9005
              name: login
            - containerPort: 9099
              name: auth
            - containerPort: 9199
              name: storage
          volumeMounts:
            - name: firebase-project
              mountPath: /home/node
      volumes:
        - name: firebase-project
          hostPath:
            path: /workspaces/reyhan-projects-k8s/i-can-do-it-deploy-cloud-run
---
apiVersion: v1
kind: Service
metadata:
  name: firebase-emulator-service
  namespace: icdi
spec:
  selector:
    app: firebase-emulator
  ports:
    - port: 4000
      targetPort: 4000
      name: ui
    - port: 5000
      targetPort: 5000
      name: hosting
    - port: 5001
      targetPort: 5001
      name: functions
    - port: 8080
      targetPort: 8080
      name: firestore
    - port: 8085
      targetPort: 8085
      name: pub-sub
    - port: 9000
      targetPort: 9000
      name: realtime
    - port: 9005
      targetPort: 9005
      name: login
    - port: 9099
      targetPort: 9099
      name: auth
    - port: 9199
      targetPort: 9199
      name: storage
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: firebase-emulator
  namespace: icdi
spec:
  selector:
    matchLabels:
      app: firebase-emulator
  serviceName: firebase-emulator-service
  replicas: 2
  template:
    metadata:
      labels:
        app: firebase-emulator
    spec:
      containers:
        - name: firebase-emulator
          image: andreysenov/firebase-tools:latest
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          securityContext:
            privileged: true
          ports:
            - containerPort: 4000
              name: ui
            - containerPort: 5000
              name: hosting
            - containerPort: 5001
              name: functions
            - containerPort: 8080
              name: firestore
            - containerPort: 8085
              name: pub-sub
            - containerPort: 9000
              name: realtime
            - containerPort: 9005
              name: login
            - containerPort: 9099
              name: auth
            - containerPort: 9199
              name: storage
          volumeMounts:
            - name: firebase-data
              mountPath: /data/firebase
  volumeClaimTemplates:
    - metadata:
        name: firebase-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi
