apiVersion: v1
kind: Secret
metadata:
  name: vixun-mongodb-secret
  namespace: vixun
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: "YWRtaW4="
  MONGO_INITDB_ROOT_PASSWORD: "cGFzcw=="
---
apiVersion: v1
kind: Service
metadata:
  name: vixun-mongodb
  namespace: vixun
spec:
  selector:
    app: vixun-mongodb
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vixun-mongodb
  namespace: vixun
spec:
  selector:
    matchLabels:
      app: vixun-mongodb
  serviceName: vixun-mongodb
  replicas: 2
  template:
    metadata:
      labels:
        app: vixun-mongodb
    spec:
      containers:
        - name: vixun-mongodb
          image: mongo
          ports:
            - containerPort: 27017
              name: mongodb
          volumeMounts:
            - name: vixun-mongodb-data
              mountPath: /data/db
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: vixun-mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vixun-mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: vixun-secret
                  key: MONGODB
  volumeClaimTemplates:
    - metadata:
        name: vixun-mongodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "standard"
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: vixun-mongo-express
  namespace: vixun
spec:
  type: LoadBalancer
  selector:
    app: vixun-mongo-express
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32004
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vixun-mongo-express
  namespace: vixun
spec:
  selector:
    matchLabels:
      app: vixun-mongo-express
  template:
    metadata:
      labels:
        app: vixun-mongo-express
    spec:
      containers:
        - name: vixun-mongo-express
          image: mongo-express
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                secretKeyRef:
                  name: vixun-mongodb-secret
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: vixun-mongodb-secret
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: ME_CONFIG_MONGODB_SERVER
              value: vixun-mongodb
