apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "i-can-do-it.fullname" . }}-config
data:
  NEXT_PUBLIC_FIREBASE_CLIENT_APPID: {{ quote .Values.icdiConfigMap.data.NEXT_PUBLIC_FIREBASE_CLIENT_APPID }}
  NEXT_PUBLIC_FIREBASE_CLIENT_MESSAGINGSENDERID: {{ quote .Values.icdiConfigMap.data.NEXT_PUBLIC_FIREBASE_CLIENT_MESSAGINGSENDERID }}
  NEXT_PUBLIC_FIREBASE_CLIENT_STORAGEBUCKET: {{ quote .Values.icdiConfigMap.data.NEXT_PUBLIC_FIREBASE_CLIENT_STORAGEBUCKET }}
  NEXT_PUBLIC_FIREBASE_CLIENT_PROJECTID: {{ quote .Values.icdiConfigMap.data.NEXT_PUBLIC_FIREBASE_CLIENT_PROJECTID }}
  NEXT_PUBLIC_FIREBASE_CLIENT_AUTHDOMAIN: {{ quote .Values.icdiConfigMap.data.NEXT_PUBLIC_FIREBASE_CLIENT_AUTHDOMAIN }}
  NEXT_PUBLIC_FIREBASE_CLIENT_APIKEY: {{ quote .Values.icdiConfigMap.data.NEXT_PUBLIC_FIREBASE_CLIENT_APIKEY }}
  NEXT_PUBLIC_EMULATOR_FIRESTORE_PORT: "8080"
  NEXT_PUBLIC_EMULATOR_AUTH_PORT: "9099"
  NEXT_PUBLIC_EMULATOR_STORAGE_PORT: "9199"