apiVersion: v1
kind: Secret
metadata:
  name: {{ include "i-can-do-it.fullname" . }}-secret
type: Opaque
data:
  FIREBASE_SERVICE_ACCOUNT_KEY: {{ quote .Values.icdiSecret.data.FIREBASE_SERVICE_ACCOUNT_KEY }}