apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vixun.fullname" . }}-mongodb-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ quote .Values.vixunMongoSecret.data.MONGO_INITDB_ROOT_USERNAME }}
  MONGO_INITDB_ROOT_PASSWORD: {{ quote .Values.vixunMongoSecret.data.MONGO_INITDB_ROOT_PASSWORD }}