apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vixun.fullname" . }}-secret
type: Opaque
data:
  MONGO_URL: {{ quote .Values.vixunSecret.data.MONGO_URL }}
  CLOUDINARY_API_KEY: {{ quote .Values.vixunSecret.data.CLOUDINARY_API_KEY }}
  CLOUDINARY_API_SECRET: {{ quote .Values.vixunSecret.data.CLOUDINARY_API_SECRET }}
  CLOUDINARY_CLOUD_NAME: {{ quote .Values.vixunSecret.data.CLOUDINARY_CLOUD_NAME }}
  SESSION_NAME: {{ quote .Values.vixunSecret.data.SESSION_NAME }}
  SESSION_SECRET: {{ quote .Values.vixunSecret.data.SESSION_SECRET }}
  SPOTIFY_CLIENT_ID: {{ quote .Values.vixunSecret.data.SPOTIFY_CLIENT_ID }}
  SPOTIFY_CLIENT_SECRET: {{ quote .Values.vixunSecret.data.SPOTIFY_CLIENT_SECRET }}
  MONGODB: {{ quote .Values.vixunSecret.data.MONGODB }}