apiVersion: v1
kind: Service
metadata:
  name: {{ include "python-project-rahul.fullname" . }}
  labels:
    {{- include "python-project-rahul.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.appSettings.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "python-project-rahul.selectorLabels" . | nindent 4 }}
