apiVersion: v1
kind: Service
metadata:
  name: {{ include "vixun.fullname" . }}-mnge
spec:
  type: {{ .Values.vixunMongoExpressService.type }}
  ports:
    - port: {{ .Values.vixunMongoExpressService.port }}
      targetPort: {{ .Values.vixunMongoExpressService.port }}
      protocol: TCP
      name: vixun-mongo-express
  selector:
    app: {{ include "vixun.fullname" . }}-mnge
